### ISSUE TITLE
"Improved Map Zooming" feature makes creating item frame maps unnecessarily difficult.

### ISSUE THREAD

**Issue by lexchxn** [Apollounknowndev/remapped#1]
I'm considering adding this mod to my game, but the "Improved Map Zooming" feature means that the main reason I make maps- to create a reference wall of the surrounding area- is much harder. Rather than being able to walk off the edge of a map and create a new one, automatically having it line up for the purposes of placing on a wall or floor, I would be required to use several "intermediary maps" to count out chunk distances and ensure the center map lines up with the distance it should be at a larger size- or utilize F3+G to count chunk borders. 

Neither are particularly appealing or intuitive, and I would request this feature to be configurable so that I can use the mod, because it is otherwise immensely appealing!

**Comment by Apollounknowndev** [comment]
At some point in the near future (hopefully in the next update) I'll be adding a button in the cartography table's GUI that'll let you decide whether or not the map zooms out relative to the center of the previous map.

**Comment by lexchxn** [comment]
That's amazing! Best of both worlds, and I didn't even consider it. Thanks for sharing!

**Comment by dragon3025** [comment]
This feature doesn't seem to be working, unless I'm not understanding it. Here's a picture of the map I made, with the red square is where I used an empty map, cartography table, and viewed the zoomed out map:

![2024-07-21_11 36 21](https://github.com/user-attachments/assets/55638876-4661-4be1-89d8-d9bcd69f26d9)
![2024-07-21_11 36 23](https://github.com/user-attachments/assets/4b4f25a9-55e4-4c76-900d-3778937837f3)

**Comment by Apollounknowndev** [comment]
Adding a button turned out to be way more difficult than expected. I'll return to that idea some day, but for now I've added a simple config option for it.
