### ISSUE TITLE
Invisible map on item frames

### ISSUE THREAD

**Issue by Pnaabnloo** [Apollounknowndev/remapped#2]
version 1.21. Remapped-1.0.2
![2024-07-18_23 40 40](https://github.com/user-attachments/assets/6647456b-9a99-4b43-93b0-4fd1e6f4bba0)
![2024-07-18_23 40 38](https://github.com/user-attachments/assets/9bf4612f-105b-42d0-9957-2301f4cb27e4)

When I left it crashed
[crash-2024-07-18_23.43.06-server.txt](https://github.com/user-attachments/files/16289515/crash-2024-07-18_23.43.06-server.txt)

**Comment by dragon3025** [comment]
I placed a map on an item frame, exited, re-enter and it crashes the game. I tried with just Fabric API and Remapped on it crashed. Here's my log: https://pastebin.com/sPxwUQt2. I tried disabling the mod, removing the map, then re-enabling the mod, and the problem wasn't there anymore.

**Comment by Apollounknowndev** [comment]
Looks like the game was occasionally saving maps with the vanilla format, not Remapped's format. I've fixed the issue for a future release, but maps that crashed the game might have their colors messed up until you fill out the area again.

**Comment by Pnaabnloo** [comment]
maps are still invisible

**Comment by dragon3025** [comment]
> maps are still invisible

I'm not getting this problem anymore. Are you using 1.0.3? Have you tried this with only this mod and it's dependencies?

**Comment by Pnaabnloo** [comment]
Found it, It happends with the mod "More Culling" with "Custom item frame renderer" enabled.
