### ISSUE TITLE
Weird behavior where it is ignoring water in some areas...

### ISSUE THREAD

**Issue by draklorx** [Apollounknowndev/remapped#4]
We added this mod to the server about a month in because we liked the idea of better looking maps... we have some weirdness in the display in at least one area though...

![2024-09-14_22 49 29](https://github.com/user-attachments/assets/3080d1c1-8ab9-4a70-aeeb-bd595332ab6c)

Attached is an image of me looking over a river with my map in hand, but for some reason the map ignores the water above the center of the river and renders it as the stone/gravel/red sand/etc. that's underneath where those blocks go.

Happy to provide whatever additional details I can.

**Comment by Apollounknowndev** [comment]
Fixed in v1.0.4.
